<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-9VAR55H" ignored="0" name="Test" tests="5" failures="1" timestamp="24 Mar 2021 06:57:48 GMT" time="0.116" errors="0">
  <testcase name="show" time="0.031" classname="com.testPackage_1.TestClass_1_P1">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.testPackage_1.TestClass_1_P1.show() didn&amp;apos;t finish within the time-out 2">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testPackage_1.TestClass_1_P1.show() didn't finish within the time-out 2
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- show -->
  <testcase name="view" time="0.0" classname="com.testPackage_1.TestClass_1_P1">
    <skipped/>
  </testcase> <!-- view -->
  <testcase name="Display" time="0.0" classname="com.testPackage_1.TestClass_1_P1"/>
  <testcase name="Display" time="0.0" classname="com.testPackage_1.TestClass_1_P1"/>
  <testcase name="Display" time="0.0" classname="com.testPackage_1.TestClass_1_P1"/>
</testsuite> <!-- Test -->
